# Generated by Django 4.2.20 on 2025-04-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geo', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('internal_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sample_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GibddSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unical_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitedSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gibdd_unical_id', models.BigIntegerField(blank=True, null=True)),
                ('commerce_internal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gibdd_description', models.TextField(blank=True, null=True)),
                ('commerce_description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('gibdd', 'ГИБДД'), ('commerce', 'Коммерция'), ('both', 'ГИБДД и Коммерция')], default=None, max_length=10, null=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('updated', 'Обновлен'), ('removed', 'Удален'), (None, 'Нет статуса')], default=None, max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['gibdd_unical_id'], name='signs_unite_gibdd_u_1c7782_idx'), models.Index(fields=['commerce_internal_id'], name='signs_unite_commerc_646676_idx')],
                'unique_together': {('gibdd_unical_id', 'commerce_internal_id')},
            },
        ),
    ]
