# Generated by Django 4.2.20 on 2025-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitedsign',
            name='gibdd_unical_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
