# Generated by Django 4.2.20 on 2025-04-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0002_alter_unitedsign_gibdd_unical_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unitedsign',
            name='signs_unite_gibdd_u_1c7782_idx',
        ),
        migrations.RemoveIndex(
            model_name='unitedsign',
            name='signs_unite_commerc_646676_idx',
        ),
        migrations.AlterUniqueTogether(
            name='unitedsign',
            unique_together=set(),
        ),
    ]
