# Generated by Django 4.2.20 on 2025-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0003_remove_unitedsign_signs_unite_gibdd_u_1c7782_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitedsign',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('updated', 'Обновлен'), ('removed', 'Удален'), ('conflict', 'Конфликт'), (None, 'Нет статуса')], default=None, max_length=10, null=True),
        ),
    ]
